////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace DotNetMemo.SumServiceReference {
//    using System.Runtime.Serialization;
//    using System;
    
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
//    [System.Runtime.Serialization.DataContractAttribute(Name="SumType", Namespace="http://schemas.datacontract.org/2004/07/DotNetMemo.Services.Models")]
//    [System.SerializableAttribute()]
//    public partial class SumType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
//        [System.NonSerializedAttribute()]
//        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
//        [System.Runtime.Serialization.OptionalFieldAttribute()]
//        private int FirstField;
        
//        [System.Runtime.Serialization.OptionalFieldAttribute()]
//        private int SecondField;
        
//        [global::System.ComponentModel.BrowsableAttribute(false)]
//        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
//            get {
//                return this.extensionDataField;
//            }
//            set {
//                this.extensionDataField = value;
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public int First {
//            get {
//                return this.FirstField;
//            }
//            set {
//                if ((this.FirstField.Equals(value) != true)) {
//                    this.FirstField = value;
//                    this.RaisePropertyChanged("First");
//                }
//            }
//        }
        
//        [System.Runtime.Serialization.DataMemberAttribute()]
//        public int Second {
//            get {
//                return this.SecondField;
//            }
//            set {
//                if ((this.SecondField.Equals(value) != true)) {
//                    this.SecondField = value;
//                    this.RaisePropertyChanged("Second");
//                }
//            }
//        }
        
//        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
//        protected void RaisePropertyChanged(string propertyName) {
//            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
//            if ((propertyChanged != null)) {
//                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
//            }
//        }
//    }
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
//    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SumServiceReference.ISumService")]
//    public interface ISumService {
        
//        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISumService/Sum", ReplyAction="http://tempuri.org/ISumService/SumResponse")]
//        int Sum(DotNetMemo.SumServiceReference.SumType value);
        
//        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISumService/Sum", ReplyAction="http://tempuri.org/ISumService/SumResponse")]
//        System.Threading.Tasks.Task<int> SumAsync(DotNetMemo.SumServiceReference.SumType value);
//    }
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
//    public interface ISumServiceChannel : DotNetMemo.SumServiceReference.ISumService, System.ServiceModel.IClientChannel {
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
//    public partial class SumServiceClient : System.ServiceModel.ClientBase<DotNetMemo.SumServiceReference.ISumService>, DotNetMemo.SumServiceReference.ISumService {
        
//        public SumServiceClient() {
//        }
        
//        public SumServiceClient(string endpointConfigurationName) : 
//                base(endpointConfigurationName) {
//        }
        
//        public SumServiceClient(string endpointConfigurationName, string remoteAddress) : 
//                base(endpointConfigurationName, remoteAddress) {
//        }
        
//        public SumServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
//                base(endpointConfigurationName, remoteAddress) {
//        }
        
//        public SumServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
//                base(binding, remoteAddress) {
//        }
        
//        public int Sum(DotNetMemo.SumServiceReference.SumType value) {
//            return base.Channel.Sum(value);
//        }
        
//        public System.Threading.Tasks.Task<int> SumAsync(DotNetMemo.SumServiceReference.SumType value) {
//            return base.Channel.SumAsync(value);
//        }
//    }
//}
